<?php
require_once('./Services/Table/classes/class.ilTable2GUI.php');
require_once('./Modules/Course/classes/class.ilCourseParticipants.php');
require_once('./Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CopyUsers/classes/class.ilCopyUsersPlugin.php');

/**
 * Class cpusrUserTableGUI
 *
 * @author  Fabian Schmid <fs@studer-raimann.ch>
 * @version 1.0.0
 */
class cpusrUserTableGUI extends ilTable2GUI {

	/**
	 * @param cpusrCourseSelectorGUI $a_parent_obj
	 * @param string                 $a_parent_cmd
	 * @param int                    $source_ref_id
	 */
	public function __construct(cpusrCourseSelectorGUI $a_parent_obj, $a_parent_cmd, $source_ref_id = 0) {
		global $ilCtrl, $ilTabs, $ilToolbar, $tpl;
		/**
		 * @var $tpl       ilTemplate
		 * @var $ilCtrl    ilCtrl
		 * @var $ilTabs    ilTabsGUI
		 * @var $ilToolbar ilToolbarGUI
		 */
		$this->pl = ilCopyUsersPlugin::getInstance();
		$tpl->addJavaScript($this->pl->getDirectory() . '/templates/js/select.js');
		$this->ctrl = $ilCtrl;
		$this->tabs = $ilTabs;
		$this->setId('cpusr_list');
		parent::__construct($a_parent_obj, $a_parent_cmd);
		$this->setRowTemplate('tpl.row.html', $this->pl->getDirectory());
		$this->setTitle($this->pl->txt('usr_table_title'));
		$this->setFormAction($this->ctrl->getFormAction($this->parent_obj));
		//
		// Columns
		$this->addColumn('', NULL, '20px');
		$this->addColumn($this->pl->txt('usr_table_header_name'));
		$this->addColumn($this->pl->txt('usr_table_header_email'));
		$this->addColumn($this->pl->txt('usr_table_header_role'));
		// ...

		$this->addMultiCommand(cpusrCourseSelectorGUI::CMD_ADD, $this->pl->txt('usr_table_button_add'));
		$ilToolbar->addButton($this->pl->txt('usr_table_button_select_mem'), '#', '', '', '', 'select_mem');
		$ilToolbar->addButton($this->pl->txt('usr_table_button_select_tut'), '#', '', '', '', 'select_tut');
		$ilToolbar->addButton($this->pl->txt('usr_table_button_select_adm'), '#', '', '', '', 'select_adm');
		// Header
		//				$ilToolbar->addButton($this->pl->txt('add_new'), $this->ctrl->getLinkTarget($a_parent_obj, 'selectEntryType'));
		//		$this->setFormAction($ilCtrl->getFormAction($a_parent_obj));
		//		if (ctrlmmMenu::isOldILIAS()) {
		//			$this->addCommandButton('saveSortingOld', $this->pl->txt('save_sorting'));
		//		} else {
		//			$this->addCommandButton('saveSorting', $this->pl->txt('save_sorting'));
		//		}
		//		// $this->setExternalSorting(true);
		//		// $this->setExternalSegmentation(true);
		//		ctrlmmMenu::includeAllTypes();
		//		$this->setData(ctrlmmEntry::getAllChildsForIdAsArray($parent_id));
		$this->initData($source_ref_id);
	}


	protected function initData($source_ref_id) {
		$membersObject = ilCourseParticipants::_getInstanceByObjId(ilObject2::_lookupObjId($source_ref_id));
		$data = array();

		foreach ($membersObject->getMembers() as $member) {
			$data[] = array( 'usr_id' => $member, 'role' => IL_CRS_MEMBER );
		}

		foreach ($membersObject->getTutors() as $tutor) {
			$data[] = array( 'usr_id' => $tutor, 'role' => IL_CRS_TUTOR );
		}

		foreach ($membersObject->getAdmins() as $admin) {
			$data[] = array( 'usr_id' => $admin, 'role' => IL_CRS_ADMIN );
		}
		//		echo '<pre>' . print_r($data, 1) . '</pre>';
		$this->setData($data);
	}


	protected function fillRow($a_set) {
		$ilObjUser = new ilObjUser($a_set['usr_id']);
		$this->tpl->setVariable('USR_ID', $ilObjUser->getId());
		$this->tpl->setVariable('TYPE', $a_set['role']);
		$this->tpl->setVariable('NAME', $ilObjUser->getPresentationTitle());
		$this->tpl->setVariable('EMAIL', $ilObjUser->getEmail());
		$this->tpl->setVariable('ROLE', $this->getSelect($ilObjUser->getId(), $a_set['role']));
		//parent::fillRow($a_set); // TODO: Change the autogenerated stub
	}


	/**
	 * @param $usr_id
	 * @param $active
	 *
	 * @return string
	 */
	protected function getSelect($usr_id, $active) {
		$mem_sel = ($active == IL_CRS_MEMBER ? 'selected' : '');
		$tut_sel = ($active == IL_CRS_TUTOR ? 'selected' : '');
		$adm_sel = ($active == IL_CRS_ADMIN ? 'selected' : '');
		$select = '<select name="' . $usr_id . '">
			<option ' . $mem_sel . ' value="' . IL_CRS_MEMBER . '">Reader</option>
			<option ' . $tut_sel . ' value="' . IL_CRS_TUTOR . '">Contributor</option>
			<option ' . $adm_sel . ' value="' . IL_CRS_ADMIN . '">Manager</option>
		</select>';

		return $select;
	}
}

?>
